server:
 port: 8055

---

spring:
  profiles:
    active:
    - default 
  application:
    name: demo
        
management:
  endpoints:
    web:
      exposure:
        exclude:
        - beans
        include:
        - '*'

eureka:
  instance:
    prefer-ip-address: false
    hostname: acoustic-0
  client:
    enabled: false
    fetchRegistry: false
    register-with-eureka: false
    service-url:
     defaultZone: http://localhost:8067/eureka

---
logging:
  level:
    '[io.netty.handler.codec.string]': info
    '[com.acoustic.users]': debug
    '[org.springframework.web]': info
    '[org.springframework.boot,logging.level.web]': info
    '[com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver]': warn
  file:
    path: /app/cicd/logs/demo.log
debug: false
---
logging:
  level:
    root: INFO

test:
  flag: true
